### ISSUE TITLE
EmptyIndexError: Index 'MAIN' does not exist in FileStorage('./index_full')

### ISSUE THREAD

**Issue by SeekPoint** [pgcool/Joint-Bootstrapping-Machines#1]
ub16hp@UB16HP:~/ub16_prj/Joint-Bootstrapping-Machines/code/automatic_evaluation$ python large_scale_evaluation_freebase.py 0.5 ../../data/output/BREE/REL_ACQUIRED_ORG_ORG/relationships_baseline.txt acquired ../../resources/freebase-easy-14-04-14/freebase_facts.txt ../../data ../../data/input/sentences.txt ./index_dir
Relationships score threshold : 0.5
System output relationships   : 2687
loading the saved Freebase databases.....

Relationship Type: acquired
Arg1 Type: ORG
Arg2 Type: ORG

Calculating set B: intersection between system output and database
<Process(Process-3, started)> In Queue 2187
<Process(Process-3, started)> In Queue 1687
<Process(Process-3, started)> In Queue 1187
<Process(Process-3, started)> In Queue 687
<Process(Process-3, started)> In Queue 187
Time taken: 0.43 seconds
System output      : 2687
Found in database  : 0
Not found          : 2687

Calculating set A: correct facts from system output not in the database (proximity PMI)
Process Process-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "large_scale_evaluation_freebase.py", line 911, in proximity_pmi_a
    idx = open_dir(index)
  File "/usr/local/lib/python2.7/dist-packages/whoosh/index.py", line 123, in open_dir
    return FileIndex(storage, schema=schema, indexname=indexname)
  File "/usr/local/lib/python2.7/dist-packages/whoosh/index.py", line 421, in __init__
    TOC.read(self.storage, self.indexname, schema=self._schema)
  File "/usr/local/lib/python2.7/dist-packages/whoosh/index.py", line 616, in read
    gen = cls._latest_generation(storage, indexname)
  File "/usr/local/lib/python2.7/dist-packages/whoosh/index.py", line 593, in _latest_generation
    for filename in storage:
  File "/usr/local/lib/python2.7/dist-packages/whoosh/filedb/filestore.py", line 81, in __iter__
    return iter(self.list())
  File "/usr/local/lib/python2.7/dist-packages/whoosh/filedb/filestore.py", line 525, in list
    files = os.listdir(self.folder)
OSError: [Errno 2] No such file or directory: './index_full'

ub16hp@UB16HP:~/ub16_prj/Joint-Bootstrapping-Machines/code/automatic_evaluation$ mkdir index_full

ub16hp@UB16HP:~/ub16_prj/Joint-Bootstrapping-Machines/code/automatic_evaluation$ python large_scale_evaluation_freebase.py 0.5 ../../data/output/BREE/REL_ACQUIRED_ORG_ORG/relationships_baseline.txt acquired ../../resources/freebase-easy-14-04-14/freebase_facts.txt ../../data ../../data/input/sentences.txt ./index_dir
Relationships score threshold : 0.5
System output relationships   : 2687
loading the saved Freebase databases.....

Relationship Type: acquired
Arg1 Type: ORG
Arg2 Type: ORG

Calculating set B: intersection between system output and database
<Process(Process-3, started)> In Queue 2187
<Process(Process-3, started)> In Queue 1687
<Process(Process-3, started)> In Queue 1187
<Process(Process-3, started)> In Queue 687
<Process(Process-3, started)> In Queue 187
Time taken: 0.43 seconds
System output      : 2687
Found in database  : 0
Not found          : 2687

Calculating set A: correct facts from system output not in the database (proximity PMI)
Process Process-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "large_scale_evaluation_freebase.py", line 911, in proximity_pmi_a
    idx = open_dir(index)
  File "/usr/local/lib/python2.7/dist-packages/whoosh/index.py", line 123, in open_dir
    return FileIndex(storage, schema=schema, indexname=indexname)
  File "/usr/local/lib/python2.7/dist-packages/whoosh/index.py", line 421, in __init__
    TOC.read(self.storage, self.indexname, schema=self._schema)
  File "/usr/local/lib/python2.7/dist-packages/whoosh/index.py", line 619, in read
    % (indexname, storage))
EmptyIndexError: Index 'MAIN' does not exist in FileStorage('./index_full')
Time taken: 0.10 seconds
System output      : 2687
Found in database  : 0

**Comment by oklaM** [comment]
I got the similar problem:

Relationships score threshold : 0.5
System output relationships   : 2687
loading the saved Freebase databases.....

Relationship Type: acquired
Arg1 Type: ORG
Arg2 Type: ORG

Calculating set B: intersection between system output and database
<Process(Process-3, started)> In Queue 2187
<Process(Process-3, started)> In Queue 1687
<Process(Process-3, started)> In Queue 1187
<Process(Process-3, started)> In Queue 687
<Process(Process-3, started)> In Queue 187
Time taken: 0.51 seconds
System output      : 2687
Found in database  : 0
Not found          : 2687

Calculating set A: correct facts from system output not in the database (proximity PMI)
Process Process-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "large_scale_evaluation_freebase.py", line 911, in proximity_pmi_a
    idx = open_dir(index)
  File "/home/oak/.local/lib/python2.7/site-packages/whoosh/index.py", line 123, in open_dir
    return FileIndex(storage, schema=schema, indexname=indexname)
  File "/home/oak/.local/lib/python2.7/site-packages/whoosh/index.py", line 421, in __init__
    TOC.read(self.storage, self.indexname, schema=self._schema)
  File "/home/oak/.local/lib/python2.7/site-packages/whoosh/index.py", line 616, in read
    gen = cls._latest_generation(storage, indexname)
  File "/home/oak/.local/lib/python2.7/site-packages/whoosh/index.py", line 593, in _latest_generation
    for filename in storage:
  File "/home/oak/.local/lib/python2.7/site-packages/whoosh/filedb/filestore.py", line 81, in __iter__
    return iter(self.list())
  File "/home/oak/.local/lib/python2.7/site-packages/whoosh/filedb/filestore.py", line 525, in list
    files = os.listdir(self.folder)
OSError: [Errno 2] No such file or directory: './index_full'
Time taken: 0.13 seconds
System output      : 2687
Found in database  : 0
Correct in corpus  : 0
Not found          : 0


Traceback (most recent call last):
  File "large_scale_evaluation_freebase.py", line 1284, in <module>
    main()
  File "large_scale_evaluation_freebase.py", line 1191, in main
    assert len(system_output) == len(a) + len(b) + len(not_found)
AssertionError
