### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe6' in position 107: ordinal not in range(128)

### ISSUE THREAD

**Issue by oklaM** [pgcool/Joint-Bootstrapping-Machines#3]
/Joint-Bootstrapping-Machines/code/automatic_evaluation$ python2 index_whoosh.py ../../data/input/sentences.txt index_dir
Traceback (most recent call last):
  File "index_whoosh.py", line 96, in <module>
    main()
  File "index_whoosh.py", line 91, in main
    index_sentences(writer)
  File "index_whoosh.py", line 32, in wrapper
    result = f(*args, **kw)
  File "index_whoosh.py", line 60, in index_sentences
    s = Sentence(l, '', '', max_tokens, min_tokens, context_window)
  File "/home/oak/BASIC/bootstrapping/Joint-Bootstrapping-Machines/code/automatic_evaluation/Sentence.py", line 144, in __init__
    text_tokens = word_tokenize(sentence_no_tags.decode('utf-8'))
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe6' in position 107: ordinal not in range(128)

**Comment by oklaM** [comment]
import sys
reload(sys)
sys.setdefaultencoding('utf8')

i add these three line codes before Sentence.py  at 7-9 lines,
then 
index_sentences 603.05 seconds
